name: Publish Docker image
on:
  workflow_dispatch:
  push:
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repo
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image and push to Docker Hub
        if: steps.extract_branch.outputs.branch != 'master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: benfugate/paramountdl:${{ steps.extract_branch.outputs.branch }}
      - name: Build image and push to Docker Hub
        if: steps.extract_branch.outputs.branch == 'master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: benfugate/paramountdl:latest
